# SPDX-License-Identifier: BSD-3-Clause
# (c) Copyright IBM Corp. 2018, 2019

ARCH  ?= s390
CROSS ?=

CPU_CFLAGS  ?= -m64
CPU_LDFLAGS ?=
CPU_ASFLAGS ?= -felf64

export ARCH CROSS CPU_CFLAGS CPU_LDFLAGS CPU_ASFLAGS

RTE_OBJCOPY_TARGET = elf64-s390
RTE_OBJCOPY_ARCH = s390

export RTE_OBJCOPY_TARGET RTE_OBJCOPY_ARCH
